#!/usr/bin/python

import sys
import urllib
import json

if (len(sys.argv) < 2):
	print "Human usage: human <command>"
	exit()

comm = sys.argv[1]

url = "http://humanual-sv.appspot.com/api?term="+comm
try:
	k = urllib.urlopen(url)
	x = json.loads(k.read())
	for w in x:
		print "+"+str(w[2])
		for meta in [w[0][i:i+40] for i in range(0, len(w[0]), 40)]:
			print meta
		print
	k.close()
except:
	print "We had an error fetching the human page for "+comm+".\n Please check your spelling and internet connection."

#uneccecary comment